### ISSUE TITLE
Getting error "The template is not valid." - "Required property is missing: shell"

### ISSUE THREAD

**Issue by helio-frota** [pkgjs/action#50]
Hi I'm testing this Github action in this basic project:
https://github.com/helio-frota/node-project-validator/blob/main/.github/workflows/ci.yml

But unfortunately I'm getting the following error:

```
Error: /home/runner/work/node-project-validator/node-project-validator/./.github/tmp/post-install-steps/action.yaml (Line: 4, Col: 7): Required property is missing: shell
Error: /home/runner/work/node-project-validator/node-project-validator/./.github/tmp/post-install-steps/action.yaml (Line: 4, Col: 7): Required property is missing: shell
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/node-project-validator/node-project-validator/./.github/tmp/post-install-steps/action.yaml (Line: 4, Col: 7): Required property is missing: shell
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load /home/runner/work/node-project-validator/node-project-validator/./.github/tmp/post-install-steps/action.yaml
```

![2022-06-27_08-39](https://user-images.githubusercontent.com/6443576/175932982-4027d5f1-e15b-4c6c-be96-8a40a634a664.png)

Please let me know if I'm doing something wrong on the configuration.
Thanks

**Comment by helio-frota** [comment]
hi folks I decided to follow the **note** in the docs here https://github.com/pkgjs/action/blob/1ef35747dd4349b7a5e0bb87fa2b6744a1bca068/docs/USAGE.md#post-install-steps

And also updated to v0.1 and it is working 

thanks
